<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TypecongeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypecongeRepository extends EntityRepository
{
    public function updateStatus($status,$id)
    {
        $qBDelege = $this->getEntityManager()->createQueryBuilder();
        $qBDelege->update('AppBundle:Typeconge', 't')
            ->set('t.typecongeStatus', $status)
            ->where('t.id = :id')
            ->setParameter('id', $id)
            ->getQuery()
            ->execute();
    }
}
